_target_: src.models.diffusion_module.DiffusionModule

diffusion_model: 
  _target_: src.models.diffusion.DiffusionModel.DiffusionModel
  time_steps: 50
  cfg_prob: 0.5

optimizer:
  _target_: torch.optim.Adam 
  
  _partial_: True
  lr: 1e-5
cfg_scale: 4.0 