_target_: src.models.latentdiffusion_module.LatentDiffusionModule

diffusion_model: 
  _target_: src.models.diffusion.LatentDiffusion.LatentDiffusion 

  time_steps: 1000
  schedule: "cosine"
  vae_image_path: ${checkpoints_dir}/vae_image/epoch=249-step=209000.ckpt
  vae_mask_path: ${checkpoints_dir}/vae_mask/epoch=99-step=83600.ckpt
  denoise_net: 
    _target_: src.models.diffusion.UNet.UNet

    in_ch: 3
    t_emb_dim: 256 
    base_channel: 64
    multiplier: [1, 2, 2, 4] 
    use_attention: True 
    ratio: 1.0 

sampler:
  _target_: src.models.diffusion.DDIM.DDIMSampler
  
  diffusion_model: ${model.diffusion_model} 
  num_samples: 4
  image_size: 64 
  channels: 3 
  reduce_steps: 50  
  device: "cuda"
  w: 4.0

optimizer:
  _target_: torch.optim.Adam 
  
  _partial_: True
  lr: 1e-5


