_target_: src.models.diffusion_test_module.DiffusionTestModule

diffusion_model: 
  _target_: src.models.diffusion.DiffusionModel.DiffusionModel
  time_steps: 1000


optimizer:
  _target_: torch.optim.Adam 
  
  _partial_: True
  lr: 1e-5
