_target_: src.models.fm_latent_module.FlowMatchingLatentModule

velocity_model: 
  _target_: src.models.flow_matching.flow_matching.VelocityModel

  net: 
    _target_: src.models.flow_matching.UNet.UNet 

    in_ch: 1
    t_emb_dim: 256
    base_channel: 64
    multiplier: [1, 2, 2, 4]
    use_attention: True
    ratio: 1.0

optimizer:
  _target_: torch.optim.Adam 
  
  _partial_: True
  lr: 1e-5

w: 4.0 
num_steps: 200 
vae_mask_path: /checkpoints/vae_mask/epoch=24-step=20900.ckpt
vae_image_path: /checkpoints/vae/epoch=249-step=209000.ckpt